# Markdown渲染配置
[markup]
  [markup.goldmark.renderer]
    unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6
    ordered = false

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
