[[main]]
  name = "首页"
  url = "/"
  weight = 1

[[main]]
  name = "关于"
  url = "/about/"
  weight = 2

[[main]]
  name = "归档"
  url = "/archives/"
  weight = 3

[[main]]
  name = "搜索"
  url = "/search/"
  weight = 4

[[main]]
  name = "友链"
  url = "/links/"
  weight = 5
