baseURL = "https://kjl-code-github-io.vercel.app/"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
title = "猿小白"
theme = "stack"
paginate = 10
hasCJKLanguage = true

[languages]
[languages.zh-cn]
languageName = "简体中文"
weight = 1
